function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 06-Aug-2024 20:48:16

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [49.89 -0.08 0;
    -64.9 -0.5 0];
road(scenario, roadCenters, 'Name', 'Road');

roadCenters = [47.06 28.01 0;
    46.95 -27.96 0];
road(scenario, roadCenters, 'Name', 'Road1');

% Add the actors
truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [-14.4028237455621 -1.58396004110509 0.01], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.truckMesh, ...
    'PlotColor', [0.85 0.325 0.098], ...
    'Name', 'Truck');
waypoints = [-14.4028237455621 -1.58396004110509 0.01;
    4.34 -1.4 0.01;
    16.2 0.35 0.01;
    28.7 1.5 0;
    43.97 1.94 0.01];
speed = [30;30;30;30;30];
yaw =  [0;NaN;NaN;NaN;NaN];
trajectory(truck, waypoints, speed, 'Yaw', yaw);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-54.4095782196903 1.17049749036939 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.929 0.694 0.125], ...
    'Name', 'Car');
waypoints = [-54.4095782196903 1.17049749036939 0.01;
    38.2 1.8 0];
speed = [100;100];
trajectory(egoVehicle, waypoints, speed);

