function [allData, scenario, sensor] = Sonnenstrasse_sim()
%Sonnenstrasse_sim - Returns sensor detections
%    allData = Sonnenstrasse_sim returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = Sonnenstrasse_sim optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 19-Sep-2024 21:27:41

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    % Generate detections for the sensor
    laneDetections = [];
    ptClouds = [];
    insMeas = [];
    [objectDetections, isValidTime] = sensor(poses, time);
    numObjects = length(objectDetections);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    if isValidTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = drivingRadarDataGenerator('SensorIndex', 1, ...
    'UpdateRate', 25, ...
    'MountingLocation', [3.7 0 0.2], ...
    'RangeLimits', [0 130], ...
    'TargetReportFormat', 'Detections', ...
    'HasFalseAlarms', false, ...
    'FieldOfView', [50 5], ...
    'Profiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('GeoReference', [51.506255 7.45736 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-203.63682569381 -65.25983265339 -0.0035781650496212;
    -197.77157931578 -110.21939700105 -0.0040127977530844;
    -195.77251249323 -125.52856594797 -0.0042343355285581];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Liebigstraße');

roadCenters = [-153.24646475945 55.119502506534 -0.002075537437733;
    -152.92023594117 52.015395535623 -0.0020416388211686;
    -149.82450152426 22.943598535431 -0.0017973898011991];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Poppelsdorfer Straße');

roadCenters = [-149.82450152426 22.943598535431 -0.0017973898011991;
    -147.79073820728 3.8182964736936 -0.0017098915449831;
    -147.36040658083 -1.0214369871521 -0.0016988937042806;
    -145.14627048925 -26.010036425972 -0.0017012092146356;
    -141.11357054362 -71.481271966426 -0.0019586105765868];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Poppelsdorfer Straße');

roadCenters = [-214.51674792745 -66.113164015205 -0.0039204349356723;
    -215.73144039443 -57.501747827753 -0.0038807965377856;
    -228.7 38.9 0;
    -166.4 54.7 -0.004508823709525];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Liebigstraße');

roadCenters = [71.860655386808 31.163861373198 -0.00048016138744167;
    71.277515081683 25.701087431373 -0.00044926609339235;
    67.41070838789 -10.569058418342 -0.00036426417512825;
    59.468656144097 -85.089728957806 -0.0008445668446484;
    58.781351486092 -91.475942583213 -0.00092665270265258];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Weisbachstraße');

roadCenters = [26.113573777362 -111.07986365011 -0.0010211505918676;
    43.617341180685 -90.93093143929 -0.00079737782937173];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Weisbachstraße');

roadCenters = [188.09463139799 24.847381788992 -0.0028162377993066;
    195.70428179404 23.57932838253 -0.0030399035263695];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [188.09463139799 24.847381788992 -0.0028162377993066;
    183.15113994776 25.614881154441 -0.00267570063113;
    181.62366382244 25.659329525533 -0.0026322899498545;
    142.12452582992 26.926412262756 -0.0016371045424091;
    126.6692414551 27.860570436251 -0.0013161202090561];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [126.6692414551 27.860570436251 -0.0013161202090561;
    71.860655386808 31.163861373198 -0.00048016138744167];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [71.860655386808 31.163861373198 -0.00048016138744167;
    54.912640835605 31.975833108139 -0.00031609827481738;
    10.900590927599 36.247853779762 -0.00011235309877122];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [10.900590927599 36.247853779762 -0.00011235309877122;
    -3.5756699653326 38.495254128616 -0.00011723332950453;
    -6.6306103368931 39.22955972996 -0.00012415002902699;
    -8.3941434946676 39.774726339508 -0.00012960099498116;
    -10.817264577164 40.820555741206 -0.00013985365562519;
    -12.900176726885 41.387976196277 -0.00014737757480887;
    -47.268213081481 45.048566518446 -0.0003339681907768;
    -68.083415021901 47.329590918275 -0.00053833571327289];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [-68.083415021901 47.329590918275 -0.00053833571327289;
    -85.038278842249 49.187854264141 -0.00075550669848923;
    -102.0764464178 51.057301644594 -0.0010196162681595;
    -111.2759407441 52.069942180306 -0.0011813564610073;
    -116.66372022357 52.581849617058 -0.0012816334277304;
    -153.24646475945 55.119502506534 -0.002075537437733];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [174.96877517407 -76.353317075874 -0.0028522669139335;
    181.80069146931 -70.823557663267 -0.0029791154831358;
    185.57068986686 -66.495487504157 -0.0030408481877373;
    188.66712796623 -60.420689869171 -0.0030710297641825;
    209.11832605557 22.723176313142 -0.0034616175327251];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [208.73374035726 88.877145082029 -0.0040281237035913;
    201.06858210907 91.624907889696 -0.0038212855373132;
    188.96682124329 95.763240000078 -0.0035128474386212];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '32936296');

roadCenters = [211.718855938 97.655522309349 -0.0042547487260904;
    219.25228445236 90.501954283729 -0.0044031689767934];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '54756695');

roadCenters = [121.27980456926 -195.23397957777 -0.0041403936542252;
    129.35463264829 -183.10666715871 -0.0039388356894818;
    133.88151886501 -176.3198166864 -0.0038407252553441;
    143.67803621747 -157.28331834643 -0.0035553275077262;
    158.57744769189 -127.00959296627 -0.0032325704154204;
    162.59039667171 -118.7652534265 -0.0031744667487175];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [162.59039667171 -118.7652534265 -0.0031744667487175;
    163.56931623899 -116.26191852938 -0.0031532967742862];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [163.56931623899 -116.26191852938 -0.0031532967742862;
    168.29719031727 -101.58684264444 -0.0030252875188594;
    169.23443026978 -98.660727812285 -0.0030040764090131;
    174.58002675173 -78.422728122167 -0.0028667587947808;
    174.96877517407 -76.353317075874 -0.0028522669139335];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [174.96877517407 -76.353317075874 -0.0028522669139335;
    177.05804903223 -58.240451849924 -0.0027185860510777;
    179.74457284363 -44.466624058596 -0.0026826147637102;
    187.72111807985 -13.391990820255 -0.0027708975645044;
    195.70428179404 23.57932838253 -0.0030399035263695];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [231.49670523434 156.17807940715 -0.0061056868143652;
    228.39365439981 146.83226878043 -0.0057719222302239;
    225.5543873047 138.28752931321 -0.0054799986358773;
    211.718855938 97.655522309349 -0.0042547487260904];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [211.718855938 97.655522309349 -0.0042547487260904;
    208.73374035726 88.877145082029 -0.0040281237035913];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [209.92180093061 69.240162905173 -0.0038234955299288;
    212.43455219003 84.00419942275 -0.0040839835669289;
    212.5317032876 85.216915330509 -0.0041033098555445;
    212.25394115577 86.240477026533 -0.0041078453313119;
    211.51100537088 87.119384001695 -0.0040951670196208;
    210.83056820841 87.720148758806 -0.0040809225508127;
    208.73374035726 88.877145082029 -0.0040281237035913];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '437208460');

roadCenters = [188.09463139799 24.847381788992 -0.0028162377993066;
    185.69262852849 16.680959450912 -0.0027193982823857;
    183.65867967093 6.356147323194 -0.0026419705758141;
    181.00012862495 -11.990384423946 -0.002574234307346;
    160.18025439903 -92.430576759703 -0.0026773635374227;
    159.3541104558 -95.623705517054 -0.0027038112706208;
    157.29913974458 -102.92229012903 -0.0027665668689991];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [58.701351486092 -93.195942583213 -0.00092665270265258;
    72 -93.9 0;
    100.13 -95.31 -0.40980970754647];
marking = [laneMarking('Solid', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')];
laneSpecification = lanespec(1, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [99.024353610107 -95.091194730994 -0.40980970754647;
    121.08998889047 -96.993230255841 -0.23157249973215;
    123.83260077409 -98.317135539455 -0.10404116577;
    148.57834893051 -100.23011009101 -0.028035818628943;
    157.29913974458 -102.92229012903 -0.0027665668689991];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [-108.59250088175 -112.78100746478 -0.54636465373539;
    -115.81349769989 -113.79328437042 -1.1514476861199;
    -127.87396680171 -115.4618573852 -1.5146705753196;
    -139.1359689728 -116.98579267821 -1.6359212625678];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '502124895-502124896-502124897');

roadCenters = [99.024353610107 -95.091194730994 -0.40980970754647;
    98.476001672015 -103.80269539149 -0.76722880461331;
    98.239992030999 -107.14043331414 -1.0224887323756;
    97.26126191898 -121.24795291937 -1.1758514832071;
    95.838299759233 -142.887642267 -1.2273199810132];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '502126761-502126762-502126763-970399504');

roadCenters = [195.70428179404 23.57932838253 -0.0030399035263695;
    209.11832605557 22.723176313142 -0.0034616175327251];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [219.25228445236 90.501954283729 -0.0044031689767934;
    236.57945317771 144.27370972198 -0.0060112674321857;
    239.16174279305 154.27592285772 -0.0063415983196506;
    242.53529090676 168.87312979756 -0.0068387152320071;
    250.55967650742 200.77118327841 -0.0080730978927051;
    263.1448324708 243.04985590857 -0.010050659466756];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [209.11832605557 22.723176313142 -0.0034616175327251;
    196.55117571197 27.729282876809 -0.0030825937216026];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

roadCenters = [154.77205217179 -111.21108383805 -0.0028440883674321;
    156.68157912129 -115.50558157029 -0.00296698320129;
    159.66027770384 -116.7960808999 -0.0030642140594992;
    163.56931623899 -116.26191852938 -0.0031532967742862];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '754512974');

roadCenters = [-68.083415021901 47.329590918275 -0.00053833571327289;
    -68.715290448774 42.95716156553 -0.00051413518361088;
    -69.701295842668 36.148187854109 -0.00048256281045767];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '763585649');

roadCenters = [-69.701295842668 36.148187854109 -0.00048256281045767;
    -73.520050711284 30.863488617391 -0.00049757336199185;
    -73.742266368374 28.260055618471 -0.0004880606847113;
    -71.159520967503 22.986391623758 -0.0004375848017002];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '763585650');

roadCenters = [-71.159520967503 22.986391623758 -0.0004375848017002;
    -73.33987986909 6.6982579273981 -0.00042430778421876;
    -74.193973558509 0.30093799259 -0.00043065364325184];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '763585651');

roadCenters = [-74.193973558509 0.30093799259 -0.00043065364325184;
    -76.714602886261 -18.501618378897 -0.00048725373885539;
    -77.172903771916 -22.072991589544 -0.00050515420853969;
    -76.923707371723 -23.690128401907 -0.00050868124834163;
    -75.717817285491 -24.970165628352 -0.00050136189806311;
    -73.555233513219 -25.913103268878 -0.00048319615770416;
    -70.435956054907 -26.518941323485 -0.00045418402726477;
    -51.358409947655 -28.837801291895 -0.00027157977108594;
    -22.905436356551 -32.387137688174 -0.00012331834238033;
    -12.817049512894 -33.68889112266 -0.00010187220506452;
    -1.9440816637557 -34.946121714007 -9.6083484823595e-05];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '763585651-763602790-763602805');

roadCenters = [-71.159520967503 22.886391623758 -0.0004375848017002;
    -53.1 17.4 -0.00042597700969793;
    -46.9 36.1 -0.00044053346048045;
    -71.2 34.7 -0.00048256281045767];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '763585652');

roadCenters = [208.73374035726 88.877145082029 -0.0040281237035913;
    207.03982568082 84.126351948831 -0.65724189424976];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [207.03982568082 84.126351948831 -0.65724189424976;
    193.09298809073 41.870035839799 -0.16638770825606;
    188.09463139799 24.847381788992 -0.0028162377993066];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [195.70428179404 23.57932838253 -0.0030399035263695;
    196.55117571197 27.729282876809 -0.0030825937216026];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [196.55117571197 27.729282876809 -0.0030825937216026;
    199.97353898762 42.137322070288 -0.0032677147627531;
    206.22151569019 60.929041497321 -0.0036181748907893;
    209.92180093061 69.240162905173 -0.0038234955299288];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [209.92180093061 69.240162905173 -0.0038234955299288;
    214.70513900798 78.552654448484 -0.0040903489699247;
    219.25228445236 90.501954283729 -0.0044031689767934];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [157.29913974458 -102.92229012903 -0.0027665668689991;
    154.77205217179 -111.21108383805 -0.0028440883674321];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [154.77205217179 -111.21108383805 -0.0028440883674321;
    153.68206237179 -114.54885492144 -0.0028768896526685;
    149.96080917251 -125.83052041786 -0.0030012032580942;
    143.01092633061 -137.6796903 -0.003086821583409];
lanetypes = [laneType('Driving')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Type', lanetypes);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Hohe Straße');

roadCenters = [126.6692414551 27.860570436251 -0.0013161202090561;
    126.58610259296 20.717807513857 -0.0012872583461192;
    126.18380515557 4.5742682144953 -0.0012472760426769;
    120.80318459469 -7.1190733551863 -0.0011456445436031;
    120.8034236413 -17.176792112261 -0.0011648165176403;
    121.65086562205 -33.086658562517 -0.0012436147762358];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '1196263089-1196263090-1196263091');

roadCenters = [-167.11164148505 56.510663999658 -0.00243520989034;
    -171.3 45.7 -0.0023089117697523;
    -172.3 38.2 -0.0022182277814551;
    -169.3 26.5 -0.0021257967785129;
    -159.85023646205 24.779660248995 -0.0020471511770257;
    -149.82450152426 22.943598535431 -0.0017973898011991];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', '1196263096');

roadCenters = [-113.93795964264 -74.552672954317 -0.0014515512401019;
    -111.25135781775 -93.744724868289 -0.13776867856129;
    -108.59250088175 -112.78100746478 -0.54636465373539];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Redtenbacherstraße');

roadCenters = [-108.59250088175 -112.78100746478 -0.54636465373539;
    -104.54520939663 -142.88749504656 -0.13856758102185;
    -100.84458570501 -150.49761512836 -0.0025721310496181];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Redtenbacherstraße');

roadCenters = [-141.11357054362 -71.481271966426 -0.0019586105765868;
    -117.33317712914 -74.174318714898 -0.0015085662786163;
    -113.93795964264 -74.552672954317 -0.0014515512401019];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [-113.93795964264 -74.552672954317 -0.0014515512401019;
    -100.27376486578 -75.999314111684 -0.0012396468618192;
    -91.400365837251 -76.934048117122 -0.0011178023214171;
    -79.28449122808 -78.224843649537 -0.00097172900019871;
    -49.935582070528 -81.351564814733 -0.00071417352537395;
    18.982769510105 -88.683672801307 -0.00064507406392522];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [18.982769510105 -88.683672801307 -0.00064507406392522;
    43.617341180685 -90.93093143929 -0.00079737782937173];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [43.617341180685 -90.93093143929 -0.00079737782937173;
    58.781351486092 -91.475942583213 -0.00092665270265258];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [18.982769510105 -88.683672801307 -0.00064507406392522;
    26.113573777362 -111.07986365011 -0.0010211505918676];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Weisbachstraße');

roadCenters = [26.113573777362 -111.07986365011 -0.0010211505918676;
    34.244402240815 -152.55677180745 -0.0019172300027179];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Weisbachstraße');

roadCenters = [-203.63682569381 -65.25983265339 -0.0035781650496212;
    -141.11357054362 -71.481271966426 -0.0019586105765868];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [-256.3428529742 -70.620080536259 -0.0055319234304321;
    -214.51674792745 -63.913164015205 -0.0039204349356723];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [-214.51674792745 -63.913164015205 -0.0039204349356723;
    -203.63682569381 -65.25983265339 -0.0035781650496212];
laneSpecification = lanespec([1 1]);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Neuer Graben');

roadCenters = [-153.24646475945 55.119502506534 -0.002075537437733;
    -167.11164148505 56.510663999658 -0.00243520989034];
laneSpecification = lanespec(1);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Sonnenstraße');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-254.27 -72.03 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car_ego');
waypoints = [-254.27 -72.03 0;
    -234.3 -68.9 0;
    -213.6 -65.8 0;
    -196.5 -67.5 0;
    -171.1 -70.1 0;
    -148.7 -72.2 0;
    -137.5 -73.3 0;
    -107.1 -76.4 0;
    -88 -79.2 0;
    -84.6 -79.4 0];
speed = [65;65;65;65;65;65;65;65;65;65];
smoothTrajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car_track = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-146.863083777247 -32.3447271206629 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car_track');
waypoints = [-146.863083777247 -32.3447271206629 0;
    -145.1 -48.5 0;
    -144.24 -60.37 0.01;
    -143.5 -66.9 0;
    -141.2 -71.5 0;
    -131.3 -74.6 0;
    -91.3 -78.7 0];
speed = [40;40;40;40;40;40;40];
smoothTrajectory(car_track, waypoints, speed);

